version: '3.9'
networks:
  vaidyuti:
    name: vaidyuti
  vaidyuti-public:
    name: vaidyuti-public
    external: true

services:
  emqx:
    image: emqx/emqx:4.4.2
    restart: always
    ports:
      # - 1883:1883
      # - 8081:8081
      # - 8083:8083
      # - 8084:8084
      # - 8883:8883
      - 18083:18083
    networks:
      - vaidyuti
      - vaidyuti-public

  influxdb:
    image: influxdb:2.3.0-alpine
    restart: always
    hostname: influxdb.sandbox-1.vaidyuti
    volumes:
      - ./data/influxdb2:/var/lib/influxdb2
      - ./data/influxdb2_config.yaml:/etc/influxdb2/config.yml
    networks:
      - vaidyuti

  telegraf:
    image: telegraf
    restart: always
    hostname: telegraf.sandbox-1.vaidyuti
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - .envs/.local/.telegraf
    depends_on:
      - emqx
      - influxdb
    networks:
      - vaidyuti

  postgres:
    image: postgres
    restart: always
    hostname: postgres.sandbox-1.vaidyuti
    env_file:
      - ./.envs/.local/.postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - vaidyuti

  grafana:
    image: grafana/grafana-oss
    restart: always
    hostname: grafana.sandbox-1.vaidyuti
    depends_on:
      - influxdb
    networks:
      - vaidyuti