version: '3.9'
networks:
  vaidyuti:
    name: vaidyuti
  vaidyuti-public:
    name: vaidyuti-public
    external: true

services:
  emqx:
    image: emqx/emqx:4.4.2
    restart: always
    ports:
      # - 1883:1883
      # - 8081:8081
      # - 8083:8083
      # - 8084:8084
      # - 8883:8883
      - 18083:18083
    networks:
      - vaidyuti
      - vaidyuti-public

  influxdb:
    image: influxdb:2.3.0-alpine
    restart: always
    ports:
      - 8086:8086
    volumes:
      - ./data/influxdb2:/var/lib/influxdb2
    networks:
      - vaidyuti

  telegraf:
    image: telegraf
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - .envs/.local/.telegraf
    environment:
      - INFLUX_ORG=Vaidyuti
      - INFLUX_HOST=http://influxdb:8086
      - INFLUX_BUCKET=daeg0
      - MQTT_SERVER=tcp://emqx:1883
    depends_on:
      - emqx
      - influxdb
    networks:
      - vaidyuti

  postgres:
    image: postgres
    restart: always
    env_file:
      - ./.envs/.local/.postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - vaidyuti
