version: '3.9'

networks:
  bridge:
    name: vems

services:
  emqx:
    container_name: emqx
    image: emqx/emqx:4.4.2
    restart: always
    ports:
      - 1883:1883
      - 8081:8081
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
    networks:
      - bridge

  influxdb:
    container_name: influxdb
    image: influxdb:2.1.1
    restart: always
    ports:
      - 8086:8086
    volumes:
      - /var/lib/influxdb2
    networks:
      - bridge

  telegraf:
    container_name: telegraf
    image: telegraf
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - .envs/.local/.influxdb
    environment:
      - MQTT_SERVER=tcp://emqx:1883
    depends_on:
      - emqx
      - influxdb
    networks:
      - bridge

  postgres:
    env_file:
      - ./.envs/.local/.postgres
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    networks:
      - bridge
